--QLBH--

SELECT TOP 3 *
FROM KHACHHANG
ORDER BY DOANHSO DESC
--32. Tính tổng số sản phẩm do “Trung Quoc” sản xuất.
SELECT COUNT(MASP) AS TONGSOSP
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc'
--33. Tính tổng số sản phẩm của từng nước sản xuất.
SELECT NUOCSX, COUNT(DISTINCT MASP) AS TONGSOSP
FROM SANPHAM
GROUP BY NUOCSX
--34. Với từng nước sản xuất, tìm giá bán cao nhất, thấp nhất, trung bình của các sản phẩm.
SELECT NUOCSX, MAX(GIA) AS MAXGIA, MIN(GIA) AS MINGIA, AVG(GIA) AS AVGGIA
FROM SANPHAM
GROUP BY NUOCSX
--35. Tính doanh thu bán hàng mỗi ngày.
SELECT NGHD AS NGAY, SUM(TRIGIA) AS DOANHTHUMOINGAY
FROM HOADON
GROUP BY NGHD
ORDER BY NGHD
--36. Tính tổng số lượng của từng sản phẩm bán ra trong tháng 10/2006.
SELECT SANPHAM.MASP, SANPHAM.TENSP, SUM(CTHD.SL) AS TONGSL
FROM CTHD
JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
JOIN SANPHAM ON CTHD.MASP = SANPHAM.MASP
WHERE YEAR(HOADON.NGHD) = 2006 AND MONTH(HOADON.NGHD) = 10
GROUP BY SANPHAM.MASP, SANPHAM.TENSP
--37. Tính doanh thu bán hàng của từng tháng trong năm 2006.
SELECT MONTH(NGHD) AS THANG, SUM(TRIGIA) AS DOANHTHU
FROM HOADON
GROUP BY MONTH(NGHD)
--38. Tìm hóa đơn có mua ít nhất 4 sản phẩm khác nhau.
SELECT SOHD
FROM CTHD
GROUP BY SOHD
HAVING COUNT(DISTINCT MASP) >= 4
--39. Tìm hóa đơn có mua 3 sản phẩm do “Viet Nam” sản xuất (3 sản phẩm khác nhau).
SELECT HOADON.SOHD
FROM CTHD
JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
JOIN SANPHAM ON CTHD.MASP = SANPHAM.MASP
WHERE SANPHAM.NUOCSX = 'Viet Nam'
GROUP BY HOADON.SOHD
HAVING COUNT(DISTINCT SANPHAM.MASP) >= 3
--40. Tìm khách hàng (MAKH, HOTEN) có số lần mua hàng nhiều nhất.
SELECT TOP 1 KHACHHANG.MAKH, KHACHHANG.HOTEN
FROM KHACHHANG
JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH
GROUP BY KHACHHANG.MAKH, KHACHHANG.HOTEN
ORDER BY COUNT(HOADON.SOHD) DESC

SELECT * FROM SANPHAM
SELECT * FROM KHACHHANG
SELECT * FROM HOADON
SELECT * FROM NHANVIEN
SELECT * FROM CTHD

--41. Tháng mấy trong năm 2006, doanh số bán hàng cao nhất ?
SELECT TOP 1 MONTH(NGHD) AS THANG
FROM HOADON
WHERE EXISTS (
		SELECT MONTH(NGHD), SUM(TRIGIA)
		FROM HOADON
		WHERE YEAR(NGHD) = 2006
		GROUP BY MONTH(NGHD)
)
--42. Tìm sản phẩm (MASP, TENSP) có tổng số lượng bán ra thấp nhất trong năm 2006.
SELECT CTHD.MASP, SANPHAM.TENSP
FROM CTHD
JOIN SANPHAM ON CTHD.MASP = SANPHAM.MASP
GROUP BY CTHD.MASP, SANPHAM.TENSP
HAVING SUM(CTHD.SL) = (
						SELECT MIN(TSL)
						FROM (
								SELECT SUM(SL) AS TSL
								FROM CTHD
								JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
								WHERE YEAR(HOADON.NGHD) = 2006
								GROUP BY MASP
						) AS MASP_MIN
)
--43. *Mỗi nước sản xuất, tìm sản phẩm (MASP,TENSP) có giá bán cao nhất.
SELECT NUOCSX, MASP, TENSP
FROM SANPHAM SP1
WHERE GIA = (
				SELECT MAX(GIA)
				FROM SANPHAM SP2
				WHERE SP1.NUOCSX = SP2.NUOCSX)
GROUP BY NUOCSX, MASP, TENSP
--44. Tìm nước sản xuất sản xuất ít nhất 3 sản phẩm có giá bán khác nhau.
SELECT NUOCSX
FROM SANPHAM
GROUP BY NUOCSX
HAVING COUNT(DISTINCT GIA) >= 3
